/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todo;
import java.util.*;

public class ToDo {
public ArrayList<String> tasks = new ArrayList<String>();

    public ArrayList<String> getTasks() {
 return tasks;
    }

    public void addTask(String task) {
      tasks.add(task);
    }

    public static void main(String[] args) {
    }
}
