/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todo;
import java.util.*;

public class ToDo {
public ArrayList<String> tasks;

    public String getTasks() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    }
}
