/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todo;
import java.util.*;

public class ToDo {
public ArrayList<String> tasks = new ArrayList<String>();

    public ArrayList<String> getTasks() {
        return tasks;
    }
    public ArrayList<String> addTask(String task) {
        return tasks;
    }

    public static void main(String[] args) {
    }
}
