/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordgame;

import org.junit.Test;
import static org.junit.Assert.*;

public class WordGameTest {
    @Test public void getsWordtoGuess() {
        WordGame game = new WordGame();
        assertEquals(game.getWordToGuess(), "B_____");
    }
}
