/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordgame;

import org.junit.Test;
import static org.junit.Assert.*;

public class WordGameTest {
    @Test public void initializesWithGameWord() {
        WordGame game = new WordGame("MAKERS");
        assertEquals(game.gameWord, "MAKERS");
    }

    @Test public void initializesWith10Attempts() {
        WordGame game = new WordGame("MAKERS");
        Integer answer = 10;
        assertEquals(game.remaining, answer);
    }

    @Test public void getsWordtoGuess() {
        WordGame game = new WordGame("MAKERS");
        assertEquals(game.getWordToGuess(), "M_____");
    }
}
