/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordgame;

public class WordGame {
    public String gameWord;

    public WordGame (String wordToGuess) {
    gameWord = wordToGuess;
}

    public String getWordToGuess() {
        return "B_____";
    }

    public static void main(String[] args) {

    }
}
