/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pricedisplay;

public class PriceDisplay {
    public static void main(String[] args) {
  String name = "Coffee machine";
  Double price = 15.99;
  System.out.printf("The price for the item %s is %.2f \n", name, price);
    }

    public String getPriceLabel(String name, double price) {
return String.format("The price for the item %s is %.2f \n", name, price);
    }
  
  }